name: macos-build

on: [push]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: configure
        run: |
          mkdir build
          cd build
          cmake ..
      - name: build
        run: |
          cd build
          make
